*#Ejercicio 3 - NumPy*

In [ ]:
#1
import numpy as np

array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#2
max = np.max(array)
min = np.min(array)
print("Minimum value:", min)
print("Maximum value:", max)

Minimum value: 1
Maximum value: 10


In [5]:
#3
array0 = np.zeros(5)
print(array0)

[0. 0. 0. 0. 0.]


In [7]:
#4
array1 = np.ones(5)
print(array1)

[1. 1. 1. 1. 1.]


In [12]:
#5
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#6
matrix.shape

(2, 3)